services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_net

  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: seeu-run
    ports:
      - "5433:5432"
    networks:
      - app_net

  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_USERNAME: "default"
      REDIS_PASSWORD: "admin"
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "6379:6379"
    networks:
      - app_net

networks:
  app_net: