x-app-common: &app-common
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy
  env_file:
    - ./.env
  networks:
    - backend_net
    - redis_net
    - db_net

services:
  app_01:
    <<: *app-common
    ports:
      - "8080:80"

  worker_01:
    build:
      context: ./jobs
      dockerfile: Dockerfile
    depends_on:
      - app_01
    env_file:
      - ./jobs/.env
    networks:
      - backend_net
      - redis_net
      - db_net

  redis:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 5s
      depend_on: false
    networks:
      - redis_net

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: seeurun
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "seeurun"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 5s
    networks:
      - db_net
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  redis_net:
    driver: bridge
  backend_net:
    driver: bridge
  db_net:
    driver: bridge

volumes:
  pg_data:
